### ISSUE TITLE
Command change

### ISSUE THREAD

**Issue by remotevase** [BoxOfDevs/UserTP#2]
I think it is "/tpa <playername>"
And "/tpaccept" or "/tpdecline" not "/tpa decline" or "/tpa accept"

**Comment by dragonwocky** [comment]
oh lol

**Comment by Thunder33345** [comment]
just use both then?

**Comment by remotevase** [comment]
Yeah, why not

**Comment by HimbeersaftLP** [comment]
Does this plugin work? Because somebody complained here: https://forums.pmmp.io/threads/plugin-not-work.750/

**Comment by remotevase** [comment]
Yes, I tested

**Comment by HimbeersaftLP** [comment]
> Hi there, me and @HimbeersaftLP are two of the main developers for this plugin.

I never contributed to it lol xD

**Comment by remotevase** [comment]
Nor did I but we are the only ones who are active in the repo who at least are developers. Thats why i said "two **of the** main"

**Comment by HimbeersaftLP** [comment]
K lol
